---
- name: managements playbook
  hosts: "mg_managements"
  roles:
    - role: bluebanquise
      tags: bluebanquise

- name: managements playbook
  hosts: "mg_managements"
  roles:
    - role: set_hostname
      tags: set_hostname
    - role: nic
      tags: nic
    - role: firewall
      tags: firewall
    - role: repositories_server
      tags: repositories_server
    - role: repositories_client
      tags: repositories_client
    - role: hosts_file
      tags: hosts_file
    - role: ssh_master
      tags: ssh_master
    - role: dhcp_server
      tags: dhcp_server
    - role: dns_server
      tags: dns_server
    - role: dns_client
      tags: dns_client
    - role: time
      tags: time
      vars:
        time_profile: server
    - role: pxe_stack
      tags: pxe_stack
    - role: nfs_server
      tags: nfs_server

- name: Primary management playbook
  hosts: management1
  roles:
    - role: conman
      tags: conman
    - role: log_server
      tags: log_server
